name: Update Blog Posts

# 매일 한국 시간 오전 1시에 이 워크플로우를 실행합니다.
on:
  schedule:
    - cron: '0 16 * * *' # UTC 16:00 (KST 01:00)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch and inject latest blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://v2.velog.io/rss/be_zion"
          readme_path: "README.md"
          comment_tag_name: "LATEST_BLOG_POSTS"
          max_post_count: 5
      committer_username: "github-actions[bot]"
      committer_email: "github-actions[bot]@users.noreply.github.com"
      commit_message: "Update README with latest blog posts"
