    name: Update Blog Posts

    # 매일 한국 시간 오전 1시에 이 워크플로우를 실행합니다.
    on:
      schedule:
        - cron: '0 16 * * *' # UTC 16:00 (KST 01:00)
      workflow_dispatch:

    jobs:
      update-readme:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Fetch and inject latest blog posts
            uses: gautamkrishnar/blog-post-workflow@v1.1.2
            with:
              # Velog 사용자 이름에 해당하는 피드 URL을 사용합니다.
              feed_list: "https://v2.velog.io/rss/be_zion"
              # README.md 파일 경로를 지정합니다.
              readme_path: "README.md"
              # 블로그 글이 들어갈 README 내 마커를 지정합니다.
              # 이 마커 사이에 최신 글 목록이 자동으로 채워집니다.
              comment_tag_name: "LATEST_BLOG_POSTS"
              # 가져올 최대 글 개수를 지정합니다. (선택 사항)
              max_post_count: 5
              # 커밋할 때 사용할 이름과 이메일입니다.
              commit_username: "github-actions[bot]"
              commit_email: "github-actions[bot]@users.noreply.github.com"
              commit_message: "Update README with latest blog posts"
    
